name: Azure Deployment (dev)

on:
  push:
    branches: [dev]

jobs:
  build:
    env:
      IMAGE_NAME: "vanlangdocker/node"
      IMAGE_TAG: "production-0.1.${{github.run_number}}"
      IMAGE_TAG_LATEST: "latest"
      AZURE_ENV: ${{ secrets.STAG_AZURE_ENV }}
      NAMESPACE: "vanlang"
      DEPLOYMENT: "vanlang-be-production"
    # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          clean: false

      - name: Inject env
        run: echo "$AZURE_ENV" > .env
        shell: bash

      - name: Log ENV Docker
        run: echo ${{ secrets.DOCKER_HUB_USERNAME }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_LATEST }}